DATA:
    ROOT: '/content/samples'
    TRAIN_FILE: '/content/train.txt'
    VAL_FILE: '/content/val.txt'
    DATASET: kinetics400
    NUM_FRAMES: 8
    NUM_CLASSES: 32
    LABEL_LIST: '/content/labels.csv'
MODEL:
    ARCH: ViT-B/32
TRAIN:
    BATCH_SIZE: 8
    ACCUMULATION_STEPS: 4